services:
  - type: web
    name: code-visualizer-api
    env: node
    plan: free
    region: frankfurt # Par défaut en Europe, modifiez si nécessaire
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: GOOGLE_API_KEY
        sync: false # À configurer manuellement dans le dashboard Render
      - key: GITHUB_TOKEN
        sync: false # À configurer manuellement dans le dashboard Render
      - key: PORT
        value: 10000
